var vcaptcha;
var vcaptcha_status;
var vcaptcha_progress_status = 'Waiting';
var c_Id;
var c_Dataset;
var c_DatasetQuestion;
var fail_repeat = false;
var vcaptcha_ValueDomain = window.location.hostname;
var vcaptcha_ValueKey;
var vcaptcha_devtoggle = false;
var widgetURL = 'https://widgetapi.vcaptcha.work';
var widgetDataset = 'https://dataset.vcaptcha.work';